sudo: required

services:
  - docker

env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

# Encrypt service-account.json and store it into travis account:
# docker run -it -v $(pwd):/usr/app ruby:2.4 sh
# gem install travis
# travis login
# copy service-account.json file into the 'volumed' directory so we can use it in the container
# travis encrypt-file service-account.json -r chivanillo/multi-k8s

before_install:
#  - openssl aes-256-cbc -K $encrypted_0c35eebf403c_key -iv $encrypte_0...
#  - curl https://sdk.cloud.google.com | bash > /dev/null;
#  - source $HOME/google-cloud-sdk/path.bash.inc
#  - gcloud components update kubectl
#  - gcloud auth activate-service-account --key-file service-account.json
#  - gcloud config set project <project_name> # i.e. skilful-berm-214822
#  - gcloud config set comput/zone us-central1-a
#  - gcloud countainer clusters get-credentials multi-cluster
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --pasword-stdin
  - docker build -t chivanillo/multi-k8s -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true chivanillo/multi-k8s npm run test -- --coverage

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
