apiVersion: v1
kind: Pod
metadata:
  name: client-pod
  labels:
    component: web
spec:
  containers:
    - name: client
      image: chivanillo/multi-worker
      resources:
        limits:
          memory: "768Mi"
          cpu: "500m"
      ports:
        - containerPort: 9999

# A Pod runs one or more closely related containers

# apiVersion: v1 Defines a different set of objects we can use
# * ComponentStatus
# * Endpoints
# * Namespace
# * ConfigMap
# * Event
# * Service: Set up networking in a Kubernetes Cluster
# * Pod:
#   - Runs a single set of containers
#   - Good for one-off dev purposes
#   - Rarely used directly in production
# Secret: Securely stores a piece of information in the cluster, such a database password
